### ISSUE TITLE
Update or Create Cyphers

### ISSUE THREAD

**Issue by cyri113** [TogetherCrew/discourse#34]
@amindadgar would you have some time today to review the cyphers.

Right now, I am just recreating the data every time I run the script, I would like to modify the queries so that it updates or creates node + edges rather than creating new ones each time.

https://github.com/TogetherCrew/discourse/blob/32-topics-etl/src/constants/cyphers.constants.ts
```[tasklist]
### Tasks
- [x] Badge HAS_GROUP BadgeGroup
- [x] Badge HAS_TYPE BadgeType
- [ ] https://github.com/TogetherCrew/discourse/issues/42
- [ ] https://github.com/TogetherCrew/discourse/issues/41
- [ ] https://github.com/TogetherCrew/discourse/issues/40
- [ ] https://github.com/TogetherCrew/discourse/issues/43
- [x] Category HAS_TOPIC Topic
- [ ] https://github.com/TogetherCrew/discourse/issues/44
- [ ] https://github.com/TogetherCrew/discourse/issues/45
- [x] Topic HAS_POST Post
- [x] Post REPLIED Post
- [ ] User BADGE_GRANTED User [TBD]
- [x] User POST Post
- [ ] https://github.com/TogetherCrew/discourse/issues/46
- [ ] User MENTIONED Post
- [ ] User HAS_JOINED Forum
```
